### ISSUE TITLE
When Bulk import failed, we cannot stop all threads from the UI

### ISSUE THREAD

**Issue by qgou** [pmonks/alfresco-bulk-import#64]
### Steps to Reproduce:
1. Prepare import files on Alfresco server, which contain illegal character in cm:name, such as double quotes, get the file location
2. Prepare target destination space in Alfresco, get nodeRef
3. Launch Bulk import url, put in above 1 and 2 parameters, start uploading
### Expected Result:

Bulk uploading should fail or When I see exception in Alfresco log, I can stop bulk import from UI
### Actual Result:

See the exception in the log, but no way to stop the process,  Bulk import process hangs and keep goes on forever according to log, but nothing more gets imported once there was an exception.

2016-09-30 13:13:28,053  ERROR [bulkimport.impl.Scanner] [BulkImport-Importer-0012] BULKIMPORT: Bulk import from 'Default' failed.
 org.alfresco.repo.node.integrity.IntegrityException: 08309395 Found 1 integrity violations:
Invalid property value:
   Node: workspace://SpacesStore/9b9c9eea-dd4f-491e-8f91-4c31a2d733ee
   Name: Costenbader, Charles M.
   Type: {http://www.ixxus.co.uk/model/ta-cms/1.0}person
   Property: {http://www.alfresco.org/model/content/1.0}name
   Constraint: 08309394 Value 'Costenbader, Charles M.' is not valid as a file name. This property must be a valid file name.

After several hours, log still shows:

2016-09-30 16:32:20,769  INFO  [bulkimport.impl.Scanner] [BulkImport-Scanner] BULKIMPORT: Multithreaded import in progress - 0 batches yet to be imported. At current rate (0.002 batches per second), estimated completion in 0d 0h 0m 0s.

When I tried to stop it from the UI: log shows error
2016-09-30 13:29:44,369  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-1177] Exception from executeScript - redirecting to status template error: 08300371 Cannot locate template processor for template org/alfresco/extension/bulkimport/stop.post.html
org.springframework.extensions.webscripts.WebScriptException: 08300371 Cannot locate template processor for template org/alfresco/extension/bulkimport/stop.post.html
        at org.springframework.extensions.webscripts.AbstractWebScript.renderTemplate(AbstractWebScript.java:963)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.renderFormatTemplate(DeclarativeWebScript.java:267)
        at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:147)
        at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:489)
        at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:551)
        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)
        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
### Environment:

Linux on AWS EC2,  MySQL RDS, Tomcat App server, JVM -openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)

Alfresco version:
Alfresco Enterprise v5.0.2
(.1 r112141-b90) schema 8033
Spring Surf and Spring WebScripts - v5.0.0
(Release)

**Comment by pmonks** [comment]
Which version of the tool are you seeing this on?

**Comment by qgou** [comment]
Bulk Import Tool v2.0.1-SNAPSHOT, Alfresco Enterprise v5.0.2 (.1 r112141-b90)

**Comment by pmonks** [comment]
Ah ok - you're using a SNAPSHOT where this is known not to work.  Can you try installing [the latest release](https://github.com/pmonks/alfresco-bulk-import/releases/tag/2.1.0) and seeing if it still occurs?

**Comment by qgou** [comment]
Thanks, Peter. Will try the latest release.

**Comment by pmonks** [comment]
@qgou any update?  Were you able to test out the latest version?

**Comment by qgou** [comment]
When I preview it: java -jar alfresco-mmt.jar install "D:\Alfresco5\amps\alfresco-bulk-import-2.1.0.amp" "D:\Alfresco5\tomcat\webapps\alfresco.war" -preview

I am getting the warning:
10170001 An error was encountered during deployment of the AMP into the WAR: 101
70000 ERROR: The amp will overwrite an existing file in the war '/WEB-INF/classe
s/alfresco/extension/templates/webscripts/org/alfresco/extension/bulkimport/fs/f
sconfig.get.html.ftl'. Execution halted.  By specifying -force , you can force i
nstallation of AMP regardless of the current war state.

I guess I can use -force option to proceed?

Thanks.

**Comment by qgou** [comment]
Hi, Peter, I use -force option and installed the amp file, but now my alfresco cannot start up: Error in the log:

2016-11-17 11:57:43,734 ERROR [org.springframework.web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'bit.fs.source' defined in file [D:\Alfresco5\tomcat\webapps\alfresco\WEB-INF\classes\alfresco\module\org.alfresco.extension.alfresco-bulk-import\context\filesystem-source-context.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.alfresco.extension.bulkimport.source.AbstractBulkImportSource.<init>(Lorg/alfresco/extension/bulkimport/source/BulkImportSourceStatus;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1076)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:980)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:633)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1081)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1877)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: org.alfresco.extension.bulkimport.source.AbstractBulkImportSource.<init>(Lorg/alfresco/extension/bulkimport/source/BulkImportSourceStatus;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:121)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:277)
	... 28 more
Caused by: java.lang.NoSuchMethodError: org.alfresco.extension.bulkimport.source.AbstractBulkImportSource.<init>(Lorg/alfresco/extension/bulkimport/source/BulkImportSourceStatus;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;)V
	at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.<init>(FilesystemBulkImportSource.java:72)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:148)
	... 30 more

**Comment by pmonks** [comment]
The first error is probably a bug in MMT where it is failing to detect that this is an upgrade of the existing AMP.  Please raise this issue with Alfresco.

The second error is likely due to inconsistencies in the exploded webapp.  If you're using Tomcat, shutdown Alfresco and delete `${ALFRESCO_HOME}/webapps/alfresco` - this will force Tomcat to re-explode `alfresco.war`.  If that doesn't work, try reapplying the bulk import AMP to a fresh `alfresco.war` file (along with any other AMPs you have installed - they will all be uninstalled when you revert to a vanilla `alfresco.war`).

**Comment by pmonks** [comment]
And just to be clear, these issues have nothing to do with the bulk import tool - they are all symptoms of Alfresco's archaic AMP / MMT module mechanism.  If you (like me) are frustrated with the limitations of the current module capabilities, please raise your concerns to Alfresco - either support or your sales rep (if you're an Enterprise customer), or on the forums (if you're a Community users).

**Comment by qgou** [comment]
Thanks, Peter. When I installed the bulk import amp, I did delete the /alfresco folder after shut down Tomcat. It is true I did not apply on top of a vanilla war since we already had bunches of customization and modules included in the war file, including the older version of bulk import tool.  It looks like we need to take out the older version of bulk import from existing war, then apply your latest version of bulk import into the war.

**Comment by pmonks** [comment]
Last I checked the MMT didn't support an "uninstall" for AMPs, which is why I'd suggest reverting to a clean alfresco.war and reinstalling those modules and customisations to bring it back to where it should be.

Note: if those customisations aren't packaged inside AMPs then this may be difficult to do repeatably - this is one of the reasons that it is strongly recommended to always package *everything* inside AMPs (despite the other flaws in the mechanism).

**Comment by pmonks** [comment]
@qgou any updates?  Were you able to get past the problems with upgrading the AMP?

**Comment by qgou** [comment]
Yup, I installed latest version:
Bulk Import Tool v2.1.0, Alfresco Enterprise v5.0.2 (.1 r112141-b90)

Tried a batch with bad cm:name and good cm:name, bulk import failed and log points out why it failed, no hanging thread anymore.

Thanks.

**Comment by pmonks** [comment]
Great!  Glad to hear you're back on track.
