### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by jorgegz** [pmonks/alfresco-bulk-import#76]
Hello.

When I run BulkImport with Bulk Import I get the Failed result attached.

![imagen](https://user-images.githubusercontent.com/34919380/40260902-080cd202-5ac3-11e8-931b-bdbb65d18661.png)

### Expected Result:
Succed Run

### Actual Result:
org.alfresco.service.namespace.NamespaceException: Namespace prefix AAdquisicionesLicitacion is not mapped to a namespace URI
	at org.alfresco.service.namespace.QName.createQName(QName.java:109)
	at org.alfresco.service.namespace.QName.createQName(QName.java:131)
	at org.alfresco.extension.bulkimport.source.fs.AbstractMapBasedMetadataLoader.loadMetadata(AbstractMapBasedMetadataLoader.java:174)
	at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportItemVersion.calculateType(FilesystemBulkImportItemVersion.java:223)
	at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportItemVersion.<init>(FilesystemBulkImportItemVersion.java:81)
	at org.alfresco.extension.bulkimport.source.fs.DirectoryAnalyser.constructImportItemVersions(DirectoryAnalyser.java:309)
	at org.alfresco.extension.bulkimport.source.fs.DirectoryAnalyser.constructImportItems(DirectoryAnalyser.java:267)
	at org.alfresco.extension.bulkimport.source.fs.DirectoryAnalyser.analyseDirectory(DirectoryAnalyser.java:159)
	at org.alfresco.extension.bulkimport.source.fs.DirectoryAnalyser.analyseDirectory(DirectoryAnalyser.java:136)
	at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:195)
	at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanDirectory(FilesystemBulkImportSource.java:245)
	at org.alfresco.extension.bulkimport.source.fs.FilesystemBulkImportSource.scanFolders(FilesystemBulkImportSource.java:161)
	at org.alfresco.extension.bulkimport.impl.Scanner.run(Scanner.java:173)
	at java.lang.Thread.run(Unknown Source)

### Environment:
Windows Server, SQL Server 2016, Tomcat, Alfresco 5.2

**Comment by pmonks** [comment]
This indicates one of two things:

1. You have a custom metadata model that hasn't been registered properly.  This [troubleshooting tip](https://github.com/pmonks/alfresco-bulk-import/wiki/Troubleshooting#validating-that-custom-content-models-have-been-deployed-to-the-repository) will help.
2. You have a typo in one of your shadow metadata files; specifically one of them is using the `AAdquisicionesLicitacion` prefix, but that doesn't exist in any of your metadata models.
